name:                phonetics-modeling
version:             0.1.0.0
github:              "elsanussi-s-mneina/phonetics-modeling"
license:             MIT
author:              "Elsanussi S. Mneina"
maintainer:          ""
copyright:           "2019 Elsanussi S. Mneina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elsanussi-s-mneina/phonetics-modeling#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  phonetics-modeling-console-exe:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Wno-unsafe
    - -Wno-safe
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-uni-patterns
    - -Wno-missing-export-lists
    - -Wno-missing-import-lists
    dependencies:
    - text
    - phonetics-modeling

library:
  source-dirs:
  - src
  ghc-options:
  - -Weverything
  - -Werror
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-deriving-strategies
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  dependencies:
  - text

tests:
  phonetics-modeling-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - phonetics-modeling:library
    - nanospec
    - text
