-- | This module imports text used
-- to interact with the user.
-- It imports it for the language that will
-- be shown if the program was not configured
-- to show any specific language.
-- Currently, the user interface is displayed in
-- English.
module DefaultLanguageText(module EnglishUSText) where

import Prelude ()
import EnglishUSText
    ( affricateMannerUIText,
      alveolarPlaceUIText,
      alveoloPalatalPlaceUIText,
      anteriorPhonemeFeatureUIText,
      applicationTitle,
      approximantMannerUIText,
      atrPhonemeFeatureUIText,
      backBacknessUIText,
      backPhonemeFeatureUIText,
      beforeServerStartMessage,
      bilabialPlaceUIText,
      centralBacknessUIText,
      clickAirstreamUIText,
      closeHeightUIText,
      closeMidHeightUIText,
      consonantUIText,
      consonantalPhonemeFeatureUIText,
      constrictedGlottisPhonemeFeatureUIText,
      continuantPhonemeFeatureUIText,
      coronalPhonemeFeatureUIText,
      creakyVoicedVocalFoldsUIText,
      delayedReleasePhonemeFeatureUIText,
      dentalPlaceUIText,
      describePhonemeUIText,
      distributedPhonemeFeatureUIText,
      dorsalPhonemeFeatureUIText,
      englishPhonemeInventoryHeader,
      epiglottalPlaceUIText,
      extraShortUIText,
      featuresHeader,
      fricativeMannerUIText,
      frontBacknessUIText,
      getFeaturesOfPhonemeUIText,
      glottalPlaceUIText,
      halfLongUIText,
      highPhonemeFeatureUIText,
      implosiveAirstreamUIText,
      inputHeader,
      ipaTextToDivideMessage,
      labialPalatalPlaceUIText,
      labialPhonemeFeatureUIText,
      labialVelarPlaceUIText,
      labializedUIText,
      labioDentalPlaceUIText,
      laryngealPhonemeFeatureUIText,
      lateralApproximantMannerUIText,
      lateralFlapMannerUIText,
      lateralFricativeMannerUIText,
      lateralMannerUIText,
      lateralPhonemeFeatureUIText,
      longUIText,
      lowPhonemeFeatureUIText,
      makeAPhonemeUnvoicedUIText,
      makeAPhonemeVoicedUIText,
      menu,
      midHeightUIText,
      nasalMannerUIText,
      nasalNasalizationUIText,
      nasalPhonemeFeatureUIText,
      nearCloseHeightUIText,
      nearOpenHeightUIText,
      noAnalysisFoundMessage,
      noEnglishDescriptionFoundMessage,
      notApplicableUIText,
      openHeightUIText,
      openMidHeightUIText,
      oralNasalizationUIText,
      palatalPlaceUIText,
      palatalizedUIText,
      palatoAlveolarPlaceUIText,
      pharyngealPhonemeFeatureUIText,
      pharyngealPlaceUIText,
      pharyngealizedUIText,
      phonemeDescriptionHeader,
      phonemeToCalculateSPEMessage,
      phonemeToDescribeMessage,
      phonemeToDevoiceMessage,
      phonemeToVoiceMessage,
      phonemesSplitHeader,
      pleaseReadReadmeMessage,
      plosiveMannerUIText,
      postAlveolarPlaceUIText,
      programTerminatedNormallyMessage,
      prompt,
      pulmonicEgressiveAirstreamUIText,
      quitUIText,
      resultHeader,
      retroflexPlaceUIText,
      roundPhonemeFeatureUIText,
      roundedRoundingUIText,
      showPhonemeInventoryUIText,
      sonorantPhonemeFeatureUIText,
      sorryUnableToCalculate,
      splitTranscriptionUIText,
      spreadGlottisPhonemeFeatureUIText,
      stridentPhonemeFeatureUIText,
      syllabicPhonemeFeatureUIText,
      tapOrFlapMannerUIText,
      trillMannerUIText,
      typeAPhoneme,
      unrecognizedSelectionMessage,
      unroundedRoundingUIText,
      unvoicedPhonemeHeader,
      userInputChunkIPAByPhoneme,
      userInputDescribeAPhonemeInEnglish,
      userInputDescribeAPhonemeInSPE,
      userInputMakeAPhonemeUnvoiced,
      userInputMakeAPhonemeVoiced,
      userInputViewArabicPhonemeInventory,
      userInputViewCreePhonemeInventory,
      userInputViewEnglishPhonemeInventory,
      userInputViewIrishPhonemeInventory,
      userSelectedMessage,
      uvularPlaceUIText,
      velarPlaceUIText,
      velarizedUIText,
      voicePhonemeFeatureUIText,
      voicedAspiratedVocalFoldsUIText,
      voicedPhonemeHeader,
      voicedVocalFoldsUIText,
      voicelessAspiratedVocalFoldsUIText,
      voicelessVocalFoldsUIText,
      vowelUIText,
      userInputConvertUnicodeToIPANumbers,
      userInputConvertIPANumbersToUnicode,
      unicodeTextToIPANumbersMessage,
      ipaNumbersToUnicodeTextMessage )

