-- | This module is responsible for converting
-- IPA numbers to Unicode characters.
-- Unicode is a ubiquitous format for representing 
-- nearly all the characters and writing systems on Earth.
module IPANumberToUnicode where

import Prelude (Int, Char, (==))

import qualified IPAConstants.IPANumbers as Numbers
import IPAConstants.IPAUnicodeConstants


numberToUnicode :: Int -> Char
numberToUnicode number =
	case number of
	{
		_ | number == Numbers.latin_small_letter_p -> latin_small_letter_p;
		_ | number == Numbers.latin_small_letter_p -> latin_small_letter_p;
		_ | number == Numbers.latin_small_letter_b -> latin_small_letter_b;
		_ | number == Numbers.latin_small_letter_t -> latin_small_letter_t;
		_ | number == Numbers.latin_small_letter_d -> latin_small_letter_d;
		_ | number == Numbers.latin_small_letter_t_with_retroflex_hook -> latin_small_letter_t_with_retroflex_hook;
		_ | number == Numbers.latin_small_letter_d_with_tail -> latin_small_letter_d_with_tail;
		_ | number == Numbers.latin_small_letter_c -> latin_small_letter_c;
		_ | number == Numbers.latin_small_letter_dotless_j_with_stroke -> latin_small_letter_dotless_j_with_stroke;
		_ | number == Numbers.latin_small_letter_k -> latin_small_letter_k;
		_ | number == Numbers.latin_small_letter_g -> latin_small_letter_g;
		_ | number == Numbers.latin_small_letter_script_g -> latin_small_letter_script_g;
		_ | number == Numbers.latin_small_letter_q -> latin_small_letter_q;
		_ | number == Numbers.latin_letter_small_capital_g -> latin_letter_small_capital_g;
		_ | number == Numbers.latin_letter_glottal_stop -> latin_letter_glottal_stop;
		_ | number == Numbers.latin_small_letter_m -> latin_small_letter_m;
		_ | number == Numbers.latin_small_letter_m_with_hook -> latin_small_letter_m_with_hook;
		_ | number == Numbers.latin_small_letter_n -> latin_small_letter_n;
		_ | number == Numbers.latin_small_letter_n_with_retroflex_hook -> latin_small_letter_n_with_retroflex_hook;
		_ | number == Numbers.latin_small_letter_n_with_left_hook -> latin_small_letter_n_with_left_hook;
		_ | number == Numbers.latin_small_letter_eng -> latin_small_letter_eng;
		_ | number == Numbers.latin_letter_small_capital_n -> latin_letter_small_capital_n;
		_ | number == Numbers.latin_letter_small_capital_b -> latin_letter_small_capital_b;
		_ | number == Numbers.latin_small_letter_r -> latin_small_letter_r;
		_ | number == Numbers.latin_letter_small_capital_r -> latin_letter_small_capital_r;
		_ | number == Numbers.latin_small_letter_v_with_right_hook -> latin_small_letter_v_with_right_hook;
		_ | number == Numbers.latin_small_letter_r_with_fishhook -> latin_small_letter_r_with_fishhook;
		_ | number == Numbers.latin_small_letter_r_with_tail -> latin_small_letter_r_with_tail;
		_ | number == Numbers.latin_small_letter_phi -> latin_small_letter_phi;
		_ | number == Numbers.greek_small_letter_beta -> greek_small_letter_beta;
		_ | number == Numbers.latin_small_letter_f -> latin_small_letter_f;
		_ | number == Numbers.latin_small_letter_v -> latin_small_letter_v;
		_ | number == Numbers.greek_small_letter_theta -> greek_small_letter_theta;
		_ | number == Numbers.latin_small_letter_eth -> latin_small_letter_eth;
		_ | number == Numbers.latin_small_letter_s -> latin_small_letter_s;
		_ | number == Numbers.latin_small_letter_z -> latin_small_letter_z;
		_ | number == Numbers.latin_small_letter_esh -> latin_small_letter_esh;
		_ | number == Numbers.latin_small_letter_ezh -> latin_small_letter_ezh;
		_ | number == Numbers.latin_small_letter_s_with_hook -> latin_small_letter_s_with_hook;
		_ | number == Numbers.latin_small_letter_z_with_retroflex_hook -> latin_small_letter_z_with_retroflex_hook;
		_ | number == Numbers.latin_small_letter_c_with_cedilla -> latin_small_letter_c_with_cedilla;
		_ | number == Numbers.latin_small_letter_j_with_crossed_tail -> latin_small_letter_j_with_crossed_tail;
		_ | number == Numbers.latin_small_letter_x -> latin_small_letter_x;
		_ | number == Numbers.latin_small_letter_gamma -> latin_small_letter_gamma;
		_ | number == Numbers.greek_small_letter_chi -> greek_small_letter_chi;
		_ | number == Numbers.latin_letter_small_capital_inverted_r -> latin_letter_small_capital_inverted_r;
		_ | number == Numbers.latin_small_letter_h_with_stroke -> latin_small_letter_h_with_stroke;
		_ | number == Numbers.latin_letter_pharyngeal_voiced_fricative -> latin_letter_pharyngeal_voiced_fricative;
		_ | number == Numbers.latin_small_letter_h -> latin_small_letter_h;
		_ | number == Numbers.latin_small_letter_h_with_hook -> latin_small_letter_h_with_hook;
		_ | number == Numbers.latin_small_letter_l_with_belt -> latin_small_letter_l_with_belt;
		_ | number == Numbers.latin_small_letter_lezh -> latin_small_letter_lezh;
		_ | number == Numbers.latin_small_letter_v_with_hook -> latin_small_letter_v_with_hook;
		_ | number == Numbers.latin_small_letter_turned_r -> latin_small_letter_turned_r;
		_ | number == Numbers.latin_small_letter_turned_r_with_hook -> latin_small_letter_turned_r_with_hook;
		_ | number == Numbers.latin_small_letter_j -> latin_small_letter_j;
		_ | number == Numbers.latin_small_letter_turned_m_with_long_leg -> latin_small_letter_turned_m_with_long_leg;
		_ | number == Numbers.latin_small_letter_l -> latin_small_letter_l;
		_ | number == Numbers.latin_small_letter_l_with_retroflex_hook -> latin_small_letter_l_with_retroflex_hook;
		_ | number == Numbers.latin_small_letter_turned_y -> latin_small_letter_turned_y;
		_ | number == Numbers.latin_letter_small_capital_l -> latin_letter_small_capital_l;
		_ | number == Numbers.latin_letter_bilabial_click -> latin_letter_bilabial_click;
		_ | number == Numbers.latin_letter_dental_click -> latin_letter_dental_click;
		_ | number == Numbers.latin_letter_retroflex_click -> latin_letter_retroflex_click;
		_ | number == Numbers.latin_letter_alveolar_click -> latin_letter_alveolar_click;
		_ | number == Numbers.latin_letter_lateral_click -> latin_letter_lateral_click;
		_ | number == Numbers.latin_small_letter_b_with_hook -> latin_small_letter_b_with_hook;
		_ | number == Numbers.latin_small_letter_d_with_hook -> latin_small_letter_d_with_hook;
		_ | number == Numbers.latin_small_letter_dotless_j_with_stroke_and_hook -> latin_small_letter_dotless_j_with_stroke_and_hook;
		_ | number == Numbers.latin_small_letter_g_with_hook -> latin_small_letter_g_with_hook;
		_ | number == Numbers.latin_letter_small_capital_g_with_hook -> latin_letter_small_capital_g_with_hook;
		_ | number == Numbers.modifier_letter_apostrophe -> modifier_letter_apostrophe;
		_ | number == Numbers.latin_small_letter_i -> latin_small_letter_i;
		_ | number == Numbers.latin_small_letter_y -> latin_small_letter_y;
		_ | number == Numbers.latin_small_letter_i_with_stroke -> latin_small_letter_i_with_stroke;
		_ | number == Numbers.latin_small_letter_u_bar -> latin_small_letter_u_bar;
		_ | number == Numbers.latin_small_letter_turned_m -> latin_small_letter_turned_m;
		_ | number == Numbers.latin_small_letter_u -> latin_small_letter_u;
		_ | number == Numbers.latin_letter_small_capital_i -> latin_letter_small_capital_i;
		_ | number == Numbers.latin_letter_small_capital_y -> latin_letter_small_capital_y;
		_ | number == Numbers.latin_small_letter_upsilon -> latin_small_letter_upsilon;
		_ | number == Numbers.latin_small_letter_e -> latin_small_letter_e;
		_ | number == Numbers.latin_small_letter_o_with_stroke -> latin_small_letter_o_with_stroke;
		_ | number == Numbers.latin_small_letter_reversed_e -> latin_small_letter_reversed_e;
		_ | number == Numbers.latin_small_letter_barred_o -> latin_small_letter_barred_o;
		_ | number == Numbers.latin_small_letter_rams_horn -> latin_small_letter_rams_horn;
		_ | number == Numbers.latin_small_letter_o -> latin_small_letter_o;
		_ | number == Numbers.latin_small_letter_schwa -> latin_small_letter_schwa;
		_ | number == Numbers.latin_small_letter_open_e -> latin_small_letter_open_e;
		_ | number == Numbers.latin_small_ligature_oe -> latin_small_ligature_oe;
		_ | number == Numbers.latin_small_letter_reversed_open_e -> latin_small_letter_reversed_open_e;
		_ | number == Numbers.latin_small_letter_closed_reversed_open_e -> latin_small_letter_closed_reversed_open_e;
		_ | number == Numbers.latin_small_letter_turned_v -> latin_small_letter_turned_v;
		_ | number == Numbers.latin_small_letter_open_o -> latin_small_letter_open_o;
		_ | number == Numbers.latin_small_letter_ae -> latin_small_letter_ae;
		_ | number == Numbers.latin_small_letter_turned_a -> latin_small_letter_turned_a;
		_ | number == Numbers.latin_small_letter_a -> latin_small_letter_a;
		_ | number == Numbers.latin_letter_small_capital_oe -> latin_letter_small_capital_oe;
		_ | number == Numbers.latin_small_letter_alpha -> latin_small_letter_alpha;
		_ | number == Numbers.latin_small_letter_turned_alpha -> latin_small_letter_turned_alpha;
		_ | number == Numbers.latin_small_letter_turned_w -> latin_small_letter_turned_w;
		_ | number == Numbers.latin_small_letter_w -> latin_small_letter_w;
		_ | number == Numbers.latin_small_letter_turned_h -> latin_small_letter_turned_h;
		_ | number == Numbers.latin_letter_small_capital_h -> latin_letter_small_capital_h;
		_ | number == Numbers.latin_letter_reversed_glottal_stop_with_stroke -> latin_letter_reversed_glottal_stop_with_stroke;
		_ | number == Numbers.latin_letter_glottal_stop_with_stroke -> latin_letter_glottal_stop_with_stroke;
		_ | number == Numbers.latin_small_letter_c_with_curl -> latin_small_letter_c_with_curl;
		_ | number == Numbers.latin_small_letter_z_with_curl -> latin_small_letter_z_with_curl;
		_ | number == Numbers.latin_small_letter_turned_r_with_long_leg -> latin_small_letter_turned_r_with_long_leg;
		_ | number == Numbers.latin_small_letter_heng_with_hook -> latin_small_letter_heng_with_hook;
		_ | number == Numbers.combining_double_inverted_breve -> combining_double_inverted_breve;
		_ | number == Numbers.combining_double_breve_below -> combining_double_breve_below;
		_ | number == Numbers.modifier_letter_vertical_line -> modifier_letter_vertical_line;
		_ | number == Numbers.modifier_letter_low_vertical_line -> modifier_letter_low_vertical_line;
		_ | number == Numbers.modifier_letter_triangular_colon -> modifier_letter_triangular_colon;
		_ | number == Numbers.modifier_letter_half_triangular_colon -> modifier_letter_half_triangular_colon;
		_ | number == Numbers.combining_breve -> combining_breve;
		_ | number == Numbers.vertical_line -> vertical_line;
		_ | number == Numbers.double_vertical_line -> double_vertical_line;
		_ | number == Numbers.full_stop -> full_stop;
		_ | number == Numbers.undertie -> undertie;
		_ | number == Numbers.combining_ring_below -> combining_ring_below;
		_ | number == Numbers.combining_caron_below -> combining_caron_below;
		_ | number == Numbers.modifier_letter_small_h -> modifier_letter_small_h;
		_ | number == Numbers.combining_right_half_ring_below -> combining_right_half_ring_below;
		_ | number == Numbers.combining_left_half_ring_below -> combining_left_half_ring_below;
		_ | number == Numbers.combining_plus_sign_below -> combining_plus_sign_below;
		_ | number == Numbers.combining_minus_sign_below -> combining_minus_sign_below;
		_ | number == Numbers.combining_diaeresis -> combining_diaeresis;
		_ | number == Numbers.combining_x_above -> combining_x_above;
		_ | number == Numbers.combining_vertical_line_below -> combining_vertical_line_below;
		_ | number == Numbers.combining_inverted_breve_below -> combining_inverted_breve_below;
		_ | number == Numbers.modifier_letter_rhotic_hook -> modifier_letter_rhotic_hook;
		_ | number == Numbers.combining_diaeresis_below -> combining_diaeresis_below;
		_ | number == Numbers.combining_tilde_below -> combining_tilde_below;
		_ | number == Numbers.combining_seagul_below -> combining_seagul_below;
		_ | number == Numbers.modifier_letter_small_w -> modifier_letter_small_w;
		_ | number == Numbers.modifier_letter_small_j -> modifier_letter_small_j;
		_ | number == Numbers.modifier_letter_small_gamma -> modifier_letter_small_gamma;
		_ | number == Numbers.modifier_letter_small_reversed_glottal_stop -> modifier_letter_small_reversed_glottal_stop;
		_ | number == Numbers.combining_tilde_overlay -> combining_tilde_overlay;
		_ | number == Numbers.combining_up_tack_below -> combining_up_tack_below;
		_ | number == Numbers.combining_down_tack_below -> combining_down_tack_below;
		_ | number == Numbers.combining_left_tack_below -> combining_left_tack_below;
		_ | number == Numbers.combining_right_tack_below -> combining_right_tack_below;
		_ | number == Numbers.combining_bridge_below -> combining_bridge_below;
		_ | number == Numbers.combining_inverted_bridge_below -> combining_inverted_bridge_below;
		_ | number == Numbers.combining_square_below -> combining_square_below;
		_ | number == Numbers.combining_tilde -> combining_tilde;
		_ | number == Numbers.superscript_latin_small_letter_n -> superscript_latin_small_letter_n;
		_ | number == Numbers.modifier_letter_small_l -> modifier_letter_small_l;
		_ | number == Numbers.combining_left_angle_above -> combining_left_angle_above;
		_ | number == Numbers.combining_double_acute_accent -> combining_double_acute_accent;
		_ | number == Numbers.combining_acute_accent -> combining_acute_accent;
		_ | number == Numbers.combining_macron -> combining_macron;
		_ | number == Numbers.combining_grave_accent -> combining_grave_accent;
		_ | number == Numbers.combining_double_grave_accent -> combining_double_grave_accent;
		_ | number == Numbers.combining_caron -> combining_caron;
		_ | number == Numbers.combining_circumflex_accent -> combining_circumflex_accent;
		_ | number == Numbers.combining_macron_acute -> combining_macron_acute;
		_ | number == Numbers.combining_grave_macron -> combining_grave_macron;
		_ | number == Numbers.combining_grave_acute_grave -> combining_grave_acute_grave;
		_ | number == Numbers.north_east_arrow -> north_east_arrow;
		_ | number == Numbers.south_east_arrow -> south_east_arrow;
		_ | number == Numbers.downwards_arrow -> downwards_arrow;
		_ | number == Numbers.upwards_arrow -> upwards_arrow;
		_ | number == Numbers.modifier_letter_extra_high_tone_bar -> modifier_letter_extra_high_tone_bar;
		_ | number == Numbers.modifier_letter_high_tone_bar -> modifier_letter_high_tone_bar;
		_ | number == Numbers.modifier_letter_mid_tone_bar -> modifier_letter_mid_tone_bar;
		_ | number == Numbers.modifier_letter_low_tone_bar -> modifier_letter_low_tone_bar;
		_ | number == Numbers.modifier_letter_extra_low_tone_bar -> modifier_letter_extra_low_tone_bar;
		_ -> '∅'; -- not recognized
	}
